name: Deploy

env:
  SLUG: "shortcode-options"
  BUILD_DIR: "build/trunk"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: Install composer packages
        run: composer update -W

      - name: Node Build 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm install
      - run: npm run build

      - name: Deploy WordPress Plugin
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SLUG: ${{ env.SLUG }}
            BUILD_DIR: ${{ env.BUILD_DIR }}
