#
# This runs after changes are merged to `master`.
#
name: Release
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo The PR was merged
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: master

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Stable tag
        run: |
          sed -i "s/Stable tag:.*/Stable tag: \${{ steps.release.outputs.tag_name.replace(\"v\", \"\") }}/g" readme.txt
          sed -i "s/\* Version:.*/\* Version:\t\t\t\${{ steps.release.outputs.tag_name.replace(\"v\", \"\") }}/g" shortcode-options.php

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Stable tversion to ${{ steps.release.outputs.tag_name.replace('v', '') }}
          title: Update Stable tag to ${{ steps.release.outputs.tag_name.replace('v', '') }}
          branch: master
          body: Update Stable version ${{ steps.release.outputs.tag_name.replace('v', '') }} in readme.txt and shortcode-options.php files
          labels: 'auto-generated, release'

      - name: Setup PHP 7.4
        if: ${{ steps.release.outputs.releases_created }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: pcov

      - name: Install PHP dependencies
        if: ${{ steps.release.outputs.releases_created }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: '-oa --no-dev'

      - name: Install and Setup Node 16.x
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          npm install

      - name: Build The Artifact
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          npm run build

      - name: Upload zip to release
        if: ${{ steps.release.outputs.releases_created }}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'shortcode-options.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.release.outputs.tag_name }}

      - name: 🚀 Deploy WordPress Plugin
        if: ${{ steps.release.outputs.releases_created }}
        uses: 10up/action-wordpress-plugin-deploy@develop
        env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SLUG: shortcode-options
            BUILD_DIR: ./build/trunk/
            INPUT_DRY_RUN: false
            VERSION: ${{ steps.release.outputs.tag_name.replace('v', '') }}
